import{a as v,S as N,N as a}from"./assets/vendor-DzrpyaUf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",q="50364756-88b1a7bffdb2f2af78bd92cba",B=15;async function d(o,t=1){const n={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B};try{return(await v.get(P,{params:n})).data}catch(i){throw console.error("❌ Error fetching images:",i),i}}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more");let E=new N(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:w,downloads:S})=>`
    <div class="gallery-item">
      <a href="${i}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </div>`).join("");u.insertAdjacentHTML("beforeend",t)}function M(){u.innerHTML=""}function h(){E.refresh()}function g(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}function $(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const x=document.getElementById("search-form");document.querySelector(".gallery");const H=document.querySelector(".load-more");let c=1,b="",L=0;x.addEventListener("submit",O);H.addEventListener("click",A);async function O(o){o.preventDefault();const t=o.currentTarget.elements.searchQuery.value.trim();if(!t){document.body&&a.Notify.failure("Please enter a search term.");return}b=t,c=1,M(),l(),g();try{const{hits:n,totalHits:i}=await d(t,c);if(L=i,n.length===0){document.body&&a.Notify.failure("Sorry, no images match your search query. Please try again.");return}m(n),h(),document.body&&a.Notify.success(`Hooray! We found ${i} images.`),n.length<15||n.length>=i?(l(),document.body&&a.Notify.info("Вибачте, але ви досягли кінця результатів пошуку.")):$()}catch(n){document.body&&a.Notify.failure("Something went wrong. Please try again later."),console.error(n)}finally{p()}}async function A(){c+=1,g();try{const{hits:o}=await d(b,c);m(o),h(),_(),c*15>=L&&(l(),document.body&&a.Notify.info("Вибачте, але ви досягли кінця результатів пошуку."))}catch(o){document.body&&a.Notify.failure("Failed to load more images."),console.error(o)}finally{p()}}function _(){var t;const{height:o}=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect())||{height:0};o&&window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
