import{a as L,S,N as a}from"./assets/vendor-DzrpyaUf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",N="50364756-88b1a7bffdb2f2af78bd92cba";async function y(r,t=1,s=40){const i={key:N,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};try{return(await L.get(w,{params:i})).data}catch{throw new Error("Не вдалося отримати зображення з Pixabay.")}}const m=document.querySelector(".gallery");let p=null;function h(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:n,comments:g,downloads:b})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${b}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),p?p.refresh():p=new S(".gallery a",{captionsData:"alt",captionDelay:250,scrollZoom:!1,animationSpeed:300})}function v(){m.innerHTML=""}const P=document.querySelector("#search-form");document.querySelector(".gallery");const d=document.querySelector(".load-more");let l=1,c="";const u=40;let f=0;P.addEventListener("submit",$);d.addEventListener("click",q);async function $(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),l=1,v(),d.classList.add("is-hidden"),c===""){a.Notify.info("Будь ласка, введіть пошуковий запит.");return}try{const t=await y(c,l,u);if(f=t.totalHits,t.hits.length===0){a.Notify.failure("На жаль, нічого не знайдено. Спробуйте інший запит.");return}h(t.hits),a.Notify.success(`Знайдено ${f} зображень.`),f>u&&d.classList.remove("is-hidden")}catch(t){a.Notify.failure("Сталася помилка при завантаженні зображень."),console.error(t)}}async function q(){l+=1;try{const r=await y(c,l,u);h(r.hits),E();const t=Math.ceil(f/u);l>=t&&(d.classList.add("is-hidden"),a.Notify.info("Це були всі результати пошуку."))}catch(r){a.Notify.failure("Не вдалося завантажити більше зображень."),console.error(r)}}function E(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
